### PR TITLE
[Fix] #30 - fix foldering and code

### LINKED ISSUE #30: [Fix] - fix foldering and code
## 🛠 Issue

음 몇 가지를 수정하겠습니다
<br/>

## 📝 To-do

- [x] 음 ,,, 
- [x] 으음 ,,,,,,,,,

### PR DESCRIPTION
**Pull request by ena-isme**
## ⭐️ Issue

close #30 

<br/>

## 🌟 Motivation

아자아자 화이팅

### CODE REVIEW

File: Puzzle-iOS/Puzzle-iOS/Resource/UIComponents/PuzzleBottomSheetViewController.swift [hunk 1]
```diff
@@ -66,12 +80,8 @@ final class PuzzleBottomSheetViewController: UIViewController {
...
 
     private func setHierarchy() {
-        [dimmedView, bottomSheetView].forEach {
-            self.view.addSubview($0)
-        }
-        [insertView, completeButton, cancelButton].forEach {
-            bottomSheetView.addSubview($0)
-        }
+        self.view.addSubviews(dimmedView, bottomSheetView)
+        bottomSheetView.addSubviews(insertView, completeButton, cancelButton)
```
Comment (thingineeer) [inline Puzzle-iOS/Puzzle-iOS/Resource/UIComponents/PuzzleBottomSheetViewController.swift:84]: 깔끔하죠ㅋ?

**Review by thingineeer — APPROVED** [review]
굿 새복많~
